apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-prometheus-deployment
    name: amin
  name: python-prometheus-deployment
  namespace: amin-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-prometheus-deployment
      name: amin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-prometheus-deployment
        name: amin
    spec:
      containers:
        - image: ghcr.io/aminsaedi/prometheus-python-playground:v1.7
          name: prometheus-python-playground
          ports:
            - containerPort: 8000
            - containerPort: 8080
          resources: {}
status: {}
