apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-prometheus-service
  name: python-prometheus-service
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-prometheus-service
  type: ClusterIP
status:
  loadBalancer: {}
