apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-prometheus-service
  name: python-prometheus-service
  namespace: amin-python
spec:
  ports:
    - name: metrics-expose
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: app-expose
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-prometheus-deployment
  type: ClusterIP
status:
  loadBalancer: {}
